### ISSUE TITLE
powerstage

### ISSUE THREAD

**Issue by kavruk** [kavruk/DbW#2]
![image](https://cloud.githubusercontent.com/assets/16322780/12646223/6266b5f2-c5d7-11e5-8685-11767c8ad428.png)

diodele de flywheel iti zic mai tarziu ce-i cu ele

**Comment by RaceAutoElectro** [comment]
![image](https://cloud.githubusercontent.com/assets/16323758/12706246/0dd1a998-c889-11e5-9691-01d7f1375058.png)

**Comment by RaceAutoElectro** [comment]
- l6203 driver 

![image](https://cloud.githubusercontent.com/assets/16323758/12706282/fc6b5a86-c889-11e5-922a-fa7e9c2beb58.png)
